"""
PDF form-filling with hard validation against overflow/injection risks.

Approach: rather than assuming a fillable AcroForm PDF exists on disk (which
would require shipping real government PDFs we don't have redistribution
rights to for a hackathon demo), this module renders a clean base page with
reportlab and overlays validated field values at fixed coordinates. The
validation step is the security-relevant part and is identical to what you'd
run before writing into a real AcroForm field:

  1. Every value is coerced to a string and control characters stripped.
  2. Every value is hard-truncated to the field's max_chars (defined per
     template in templates.py) -- this is what prevents a field from
     overflowing into neighboring form regions or blowing up PDF stream size.
  3. Every field's (x, y) coordinate is bounds-checked against the page
     dimensions before drawing -- a malformed/tampered template config can
     never cause reportlab to attempt an out-of-bounds draw call.
  4. Total number of fields written is capped, and the whole render runs
     inside a try/except that never lets a rendering exception leak a stack
     trace back to the client.
"""
from __future__ import annotations

import logging
import re
import uuid
from datetime import datetime, timezone
from io import BytesIO
from pathlib import Path

from pypdf import PdfReader, PdfWriter
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

from app.config import FILLED_FORMS_DIR, get_settings
from app.pdf.templates import PAGE_HEIGHT, PAGE_WIDTH, FormTemplate, get_template

logger = logging.getLogger("civicmint.pdf.form_filler")

_CONTROL_CHAR_RE = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")
_MAX_FIELDS_PER_FORM = 40


class FormValidationError(ValueError):
    """Raised when a template or field value fails validation before rendering."""


def _sanitize_value(value: object, max_chars: int) -> str:
    text = "" if value is None else str(value)
    text = _CONTROL_CHAR_RE.sub("", text).replace("\r", " ").strip()
    settings = get_settings()
    hard_cap = min(max_chars, settings.PDF_MAX_FIELD_CHARS)
    if len(text) > hard_cap:
        text = text[:hard_cap].rstrip() + "..."
    return text


def _validate_coordinates(x: float, y: float) -> None:
    if not (0 <= x <= PAGE_WIDTH) or not (0 <= y <= PAGE_HEIGHT):
        raise FormValidationError(f"Field coordinate ({x}, {y}) is outside page bounds.")


def _wrap_text(text: str, max_chars_per_line: int = 95) -> list[str]:
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if len(candidate) > max_chars_per_line:
            if current:
                lines.append(current)
            current = word
        else:
            current = candidate
    if current:
        lines.append(current)
    return lines


def render_form(template: FormTemplate, field_values: dict[str, object]) -> bytes:
    if len(field_values) > _MAX_FIELDS_PER_FORM:
        raise FormValidationError("Too many fields submitted for a single form render.")

    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)

    # Header
    c.setFont("Helvetica-Bold", 13)
    _validate_coordinates(50, 740)
    c.drawString(50, 740, template.title[:120])
    c.setFont("Helvetica", 8)
    c.drawString(50, 725, "Generated by CivicMint -- for reference; verify against the official form before submission.")
    c.line(50, 715, PAGE_WIDTH - 50, 715)

    fields_written = 0
    for field_name, spec in template.fields.items():
        _validate_coordinates(spec.x, spec.y)
        raw_value = field_values.get(field_name, "")
        clean_value = _sanitize_value(raw_value, spec.max_chars)
        if not clean_value:
            continue

        c.setFont("Helvetica", spec.font_size)
        # Label above the value for readability
        label = field_name.replace("_", " ").title()
        c.setFont("Helvetica-Oblique", 7)
        _validate_coordinates(spec.x, spec.y + 10)
        c.drawString(spec.x, spec.y + 10, label)

        c.setFont("Helvetica", spec.font_size)
        if len(clean_value) > 95:
            for i, line in enumerate(_wrap_text(clean_value)):
                y = spec.y - (i * (spec.font_size + 2))
                _validate_coordinates(spec.x, y)
                c.drawString(spec.x, y, line)
        else:
            c.drawString(spec.x, spec.y, clean_value)
        fields_written += 1

    c.showPage()
    c.save()
    buffer.seek(0)

    # Round-trip through pypdf as a structural validation pass -- if
    # reportlab produced anything malformed, this raises here (server-side)
    # rather than shipping a corrupt file to the client.
    reader = PdfReader(buffer)
    writer = PdfWriter()
    for page in reader.pages:
        writer.add_page(page)

    out_buffer = BytesIO()
    writer.write(out_buffer)
    return out_buffer.getvalue()


def fill_form(template_id: str, field_values: dict[str, object]) -> tuple[str, Path, int]:
    """
    Validates, renders, and persists a filled form.
    Returns (filename, full_path, fields_written_count).
    Raises FormValidationError for any caller-facing validation failure.
    """
    template = get_template(template_id)
    if template is None:
        raise FormValidationError(f"Unknown form template_id: {template_id!r}")

    field_values = dict(field_values)
    field_values.setdefault(
        "date_generated", datetime.now(timezone.utc).strftime("%Y-%m-%d")
    )

    pdf_bytes = render_form(template, field_values)

    FILLED_FORMS_DIR.mkdir(parents=True, exist_ok=True)
    filename = f"{template_id}_{uuid.uuid4().hex[:10]}.pdf"
    out_path = FILLED_FORMS_DIR / filename
    out_path.write_bytes(pdf_bytes)

    non_empty = sum(1 for v in field_values.values() if str(v).strip())
    logger.info("Rendered form template=%s fields_written=%d file=%s", template_id, non_empty, filename)
    return filename, out_path, non_empty
